### ISSUE TITLE
Fix "couldn't resolve module/action 'k8s_exec'"

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-content-testing#4]
After working through #1, the local role I'm running is running into an issue where Ansible can't find the module that I used successfully in the playbook when the same task is copied into a role I created locally using `ansible-galaxy init replay` in the `roles/` directory:

```
TASK [include_role : replay] ***************************************************
ERROR! couldn't resolve module/action 'k8s_exec'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/jgeerling/Development/GitHub/ansible-content-testing/roles/replay/tasks/main.yml': line 10, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Test the k8s_exec module from the collection (in replay).
  ^ here

```

This seems to be me running into this annoying issue again: https://github.com/ansible/ansible/issues/68198

**Comment by geerlingguy** [comment]
Apparently that issue's also been locked in addition to closed, so... I guess this will never change and I'll need to add an extra step into the process for every role I create that uses any modules that aren't in Ansible core.

Grr.

**Comment by geerlingguy** [comment]
So before the steps were:

    ansible-galaxy init myrole
    [copy tasks into new role main/tasks.yml]
    [run playbook]

And copy and paste tasks from playbook into `myrole`.

Now steps are:

    ansible-galaxy init myrole
    [copy tasks into new role main/tasks.yml]
    [run playbook]
    <playbook run breaks>
    [figure out which tasks I just copied and pasted require which collections in the playbook]
    nano myrole/metadata/main.yml
    [edit to add `collections:` stuff from playbook]
    [save file]
    [run playbooks]

And finally the tasks in the role should work the same as they did in the playbook.

Now, for many of my playbooks, where I may have multiple collections defined, I will have to also figure out which ones to add to my _role_ meta file, since I may have one or more on the playbook level that are not needed in the role.

This is a lot more mental burden.

**Comment by alex-mesfin** [comment]
> So before the steps were:
> 
> ```
> ansible-galaxy init myrole
> [copy tasks into new role main/tasks.yml]
> [run playbook]
> ```
> 
> And copy and paste tasks from playbook into `myrole`.
> 
> Now steps are:
> 
> ```
> ansible-galaxy init myrole
> [copy tasks into new role main/tasks.yml]
> [run playbook]
> <playbook run breaks>
> [figure out which tasks I just copied and pasted require which collections in the playbook]
> nano myrole/metadata/main.yml
> [edit to add `collections:` stuff from playbook]
> [save file]
> [run playbooks]
> ```
> 
> And finally the tasks in the role should work the same as they did in the playbook.
> 
> Now, for many of my playbooks, where I may have multiple collections defined, I will have to also figure out which ones to add to my _role_ meta file, since I may have one or more on the playbook level that are not needed in the role.
> 
> This is a lot more mental burden.



> So before the steps were:
> 
> ```
> ansible-galaxy init myrole
> [copy tasks into new role main/tasks.yml]
> [run playbook]
> ```
> 
> And copy and paste tasks from playbook into `myrole`.
> 
> Now steps are:
> 
> ```
> ansible-galaxy init myrole
> [copy tasks into new role main/tasks.yml]
> [run playbook]
> <playbook run breaks>
> [figure out which tasks I just copied and pasted require which collections in the playbook]
> nano myrole/metadata/main.yml
> [edit to add `collections:` stuff from playbook]
> [save file]
> [run playbooks]
> ```
> 
> And finally the tasks in the role should work the same as they did in the playbook.
> 
> Now, for many of my playbooks, where I may have multiple collections defined, I will have to also figure out which ones to add to my _role_ meta file, since I may have one or more on the playbook level that are not needed in the role.
> 
> This is a lot more mental burden.

When you edited the meta/main.yml what exactly did you add
